### ISSUE TITLE
getAllMemoryFromIda returns only data from first segment

### ISSUE THREAD

**Issue by nazywam** [danielplohmann/apiscout#2]
Hey,

https://github.com/danielplohmann/apiscout/blob/master/apiscout/IdaTools.py#L72

`end = idc.SegEnd(start)` works correctly only if our IDA db has only segment, which is sometimes not true.

I think scanning till `getLastAddress()` instead of `idc.SegEnd()` should do the trick.

Cheers!

**Comment by danielplohmann** [comment]
just implemented what I meant by my proposed solution. :)
Now you can even have segments like
0x400000 - 0x410000
0x440000 - 0x450000

and the gap is handled correctly. ;)
