### ISSUE TITLE
DatabaseBuilder skipping some dlls

### ISSUE THREAD

**Issue by Dump-GUY** [danielplohmann/apiscout#23]
No matter if I did not use --auto option or if I modified config.py, DatabaseBuilder.py is still skipping some dlls during processing and parsing exports.

Tested on win7 sp1 professional, win10 pro.
Python 3.7

I attached a screenshot where i specified option to parse only dll from my directory and you can see that advapi32.dll, iertutil.dll, crypt32.dll etc.. are still not processed...
It's an amazing tool but could you please check this issue?
![Capture](https://user-images.githubusercontent.com/59492005/101381783-76e7b780-38b7-11eb-860a-67fcc8904dfd.PNG)

**Comment by Dump-GUY** [comment]
I hope it will help you I think I found where the problem is. If the dll has no name associated with export func like it has only ordinal the method xxx.decode throws an exception and the dll is not processed. As you can see on screenshot attached.
![Untitled](https://user-images.githubusercontent.com/59492005/101411926-0a35e280-38e2-11eb-9ca4-9c635eddccb8.png)

**Comment by danielplohmann** [comment]
thx for the fixes, all verified and integrated!
