### ISSUE TITLE
#Failed Installation with "setup.py" because of "Lief"

### ISSUE THREAD

**Issue by akhribfarouk** [danielplohmann/apiscout#28]
-------------------------------------------------------------------------------------------------
 ### Running setup.py install for lief ... error - Under windows 10 64 bits - Python 3.9.1 - pip 20.3.3
-------------------------------------------------------------------------------------------------

```
python setup.py install
```
```
.
.
Collecting lief
  Downloading lief-0.10.1.tar.gz (12.7 MB)
     |████████████████████████████████| 12.7 MB
Using legacy 'setup.py install' for lief, since package 'wheel' is not installed.
Installing collected packages: lief
    Running setup.py install for lief ... error
    ERROR: Command errored out with exit status 1:
```
-----------------------------------------------------------------------------------------------
FIX for Windows 32 bits -->
-----------------------------------------------------------------------------------------------
(make sure that your python and pip are installed )

1. Open Command prompt as Administrator
2. run this command:
```
pip install "https://lief-project.github.io/packages/lief/lief-0.11.0.dev0-cp39-cp39-win32.whl"
```
3. Re-run the install command:
```
python setup.py install
```
-----------------------------------------------------------------------------------------------
FIX for Windows 64 bits -->
-----------------------------------------------------------------------------------------------
(make sure that your python and pip are installed )

1. Open Command prompt as Administrator
2. run this command:
```
pip install "https://lief-project.github.io/packages/lief/lief-0.11.0.dev0-cp39-cp39-win_amd64.whl"
```
3. Re-run the install command:
```
python setup.py install
```
-----------------------------------------------------------------------------------------------
FIX for Other platforms -->
-----------------------------------------------------------------------------------------------
(make sure that your python and pip are installed )

1. go to this website:
```
https://lief.quarkslab.com/packages/lief/
```
2. choose your system platform
3. run:
```
pip install <YOUR CHOOSEN FILE FOR SELECTED PLATFORM> 
```
This is the official Repo of Lief:
https://github.com/lief-project/LIEF

<p align="center" >
<img width="40%" src="https://i.ibb.co/mvMs1gV/lgog.png"/>
</p>

**Comment by danielplohmann** [comment]
thanks for the comment!
using the dev snapshot for LIEF is a good workaround but aiming for a direct fix, I have now pinned the dependency to LIEF 0.10.1 and also included wheel - which this, the prebuilt binary package from PyPI should be available and usable as well (at least that worked for SMDA in this way).

**Comment by akhribfarouk** [comment]
Good for you, but why when building the Library virus total signal it as a backdoor and trojan ?
that is confusing, i did,'t look into the binary yet but there is something need to be fixed because a trojan is not what someone looking for, thank you.
